version: '3.8'
services:
  db:
    image: postgres:15.0
    environment:
      POSTGRES_DB: clinical_management_db  # Correct variable for the database name
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 10s
      retries: 5

  init-db:
    image: postgres:15.0
    depends_on:
      - db
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_USER: myuser  # Include the same user in the init-db service
      POSTGRES_PASSWORD: mypassword  # Include the password as well
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - mynetwork

  clinic-management-system-app:
    build:
      context: /Users/shoaiblatif/Documents/Personal-Projects/healthTechProject/clinic-management-system/  # Path to your app Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
