version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    image: postgres:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/clinical_management_db
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

    depends_on:
      db: # Ensure DB is started before the app
        condition: service_healthy

networks:
  mynetwork:
    driver: bridge