spring.config.import=optional:configserver: instead
##Port
server.port=8085
##Name
spring.application.name=api-gateway

spring.main.allow-bean-definition-overriding=true
##routes
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates=Path=/user/api/**
