# Application Configuration
spring.application.name=clinic-management-system
server.port=8080

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_management_system
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Flyway Configuration
flyway.enabled=false



