spring.application.name=clinic-management-system

spring.datasource.url=jdbc:postgresql://db:5432/clinical_management_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false 
server.port=8080








