# Application Configuration
spring.application.name=clinic-management-system
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/clinic_management_system
spring.datasource.username=admin
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Flyway Configuration
flyway.enabled=false

## logging
logging.level.org.springframework.security=INFO
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n

## keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/Shoaib
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs





