spring:
  application:
    name: clinic-management-system
server:
  port: 8081


  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5433/clinical_management_db
    username: clinic_user
    password: clinic_password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        boot:
          allow_jdbc_metadata_access: false
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false


# Flyway Configuration
flyway:
  enabled: false

# Logging
logging:
  level:
    org.springframework.security: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

# Security Configuration
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/clinical-management-realm
        jwk-set-uri: http://localhost:8080/realms/clinical-management-realm/protocol/openid-connect/certs

# Keycloak Configuration (properly structured)
jwt:
  auth:
    converter:
      resource-id: rest-api-doctor
      principle-attribute: preferred_username


keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD}

