# Application Name
spring.application.name=clinic-management-system

# Server Configuration
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/clinical_management_db
spring.datasource.username=clinic_user
spring.datasource.password=clinic_password
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# application.properties
app.frontend.login-url=http://localhost:5173/login

#Endpoints
app.api.registerApi=/user/api/v1/register
app.api.passwordReset=/user/api/v1/password-reset/**
app.api.verifyEmail=/user/api/v1/verify-email

# Flyway Configuration
flyway.enabled=true

# Logging Configuration
logging.level.com.example.clinicmanagementsystem.user.webConfig.SecurityConfig=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{dd-MM-yyyy HH:mm:ss} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n

# Email Configuration for mailhog
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# JWT Configuration
jwt.secret=your-256-bit-secret-key-change-this-in-production
jwt.expiration=3600000
