
#specify a trigger
#on keyword triggers when we push a commit to repo
on:
  push:
  branches:
    - main

jobs:
  build:
    runs-on: macos-latest # Or your desired runner OS

    steps:
      - name: Check Java Version
        run: |
          echo "Java Version: $JAVA_HOME"
          java -version
          if ! java -version 2>&1 | grep -q "17.*"; then
            echo "Error: Java 17 is required!"
            exit 1
          fi