name: CI/CD Pipeline
on:
  push:
    branches: [modular-monolith-change]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-test.yml

  deploy:
    needs: build
    if: success()
    uses: ./.github/workflows/deploy.yml
