name: Deploy to Render
on:
  workflow_call:  
  workflow_dispatch:  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: clinic-api

      - name: Deploy to Render
        uses: sws2apps/render-deployment@v1.8.0
        with:
          serviceId: ${{ secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ secrets.RENDER_API_KEY }}
