name: Deploy to Render
on:
  workflow_call:
    inputs:
      serviceId:
        required: true
        type: string
      apiKey:
        required: true
        type: string
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: clinic-api

      - name: Deploy to Render
        uses: sws2apps/render-deployment@v1.8.0
        with:
          serviceId: ${{ inputs.serviceId || secrets.RENDER_SERVICE_ID }}
          apiKey: ${{ inputs.apiKey || secrets.RENDER_API_KEY }}
          multipleDeployment: true
